// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackageFunctionApp.Infrastructure.Database;

#nullable disable

namespace PackageFunctionApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241027213440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("PackageFunctionApp.App.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageSupplierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("PoNumber");

                    b.HasIndex("PackageSupplierId", "PackageId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PackageFunctionApp.App.Models.Package", b =>
                {
                    b.Property<string>("SupplierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("SupplierId", "PackageId");

                    b.HasIndex("SupplierId", "PackageId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("PackageFunctionApp.App.Models.Item", b =>
                {
                    b.HasOne("PackageFunctionApp.App.Models.Package", null)
                        .WithMany("Items")
                        .HasForeignKey("PackageSupplierId", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PackageFunctionApp.App.Models.Package", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
